version: 2
jobs:
  test:
    steps:
      - checkout
      - run: 
          name: npm install
          command: npm install
      - run:
          name: Test
          command: 'npm test'

workflows:
  version: 2
  test:
    jobs:
      - test