version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@0.0.4

workflows:
  build_test_deploy:
    jobs:
      - build_test:
          context: notas
      - docker_hub_build_push_image:
          requires:
            - build_test
          context: notas
      - aws-ecr/build_and_push_image:
          region: us-east-2
          account-url: ${AWS_ECR_ACCOUNT_URL}
          repo: notas-backend
          tag: tag
          requires:
            - build_test
          context: notas
jobs:
  build_test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Setup
          command:
            npm install
  docker_hub_build_push_image:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build and push Docker image to Docker Hub
          command: |
            docker-compose build
            echo ${DOCKER_PWD} | docker login -u ${DOCKER_LOGIN} --password-stdin
            docker tag project_web:latest raymond981/notas-backend:tagname
            docker push raymond981/notas-backend:tagname


